### ISSUE TITLE
Query fails when using the $contains operator with a single value

### ISSUE THREAD

**Issue by ramsestom** [feathersjs/feathers-sequelize#135] opened 2017-07-06 21:57 UTC
### Steps to reproduce

using the `$contains` operator inside a query result in the following error: `TypeError: values.map is not a function` if the `$contains` value is not an array. The same query directly performed with sequelize (so, out of feathers) works though.
So:

```
var query = Object.assign({}, {
        $or: 
        {
            author: 1,
            targets: {
                $or: {
                    $eq: null,
                    $contains: [1]
                }
            }
        }
    });
```
works but 

```
var query = Object.assign({}, {
        $or: 
        {
            author: 1,
            targets: {
                $or: {
                    $eq: null,
                    $contains: 1
                }
            }
        }
    });
```
fails with the `TypeError: values.map is not a function` error.
Both query works when directly performed with `sequelize.findAll(query)`
And according to the sequelize docs (https://github.com/sequelize/sequelize/blob/master/docs/querying.md#range-operators) querying with 
`$contains: integer` should be supported

You can find the complete conversation regarding this issue on the feathers slack channel here: https://feathersjs.slackarchive.io/help/page-100

**Module versions** 
feathers-sequelize 2.0.1

**Comment by DesignByOnyx** [comment] 2017-07-21 12:11
I cannot reproduce this. Here are the steps I used:

1. `feathers generate app`
2. `feathers generate service` (named it "Container")

This is my model:

```js
const container = sequelizeClient.define('container', {
    targets: {
      type: Sequelize.Array(Sequelize.INTEGER)
    }
  });
```

Some test data:

```json
[
  { id: 1, targets: [0, 3, 4] },
  { id: 2,  targets: [1, 2, 3] },
  { id: 3, targets: null }
]
```

Use this as my test file:

```js
const app = require('./src/app');
const Container = app.services['container'].Model;

Container.findAll({
  raw: true,
  where: {
    targets: {
      $or: {
        $eq: null,
        $contains: 1
      }
    }
  }
}).then(result => {
  console.log('RESULT:', result);
}).catch(err => {
  console.log('ERROR:', err);
});
```

And I get the same error described by the OP:
> `TypeError: values.map is not a function`

When I change the `$contains` portion of the query to an array (`$contains: [1]`), it works.

**Comment by DesignByOnyx** [comment] 2017-07-21 13:05
I wanted to put my explanation in a separate comment.

I helped the OP norrow down this bug and asked him to report this issue here. I am not sure what he might have done differently in his testing, but I am now doubting the following claim:

> The same query directly performed with sequelize (so, out of feathers) works though.

As the example code above demonstrates, the `$contains` operator expects an array - even when querying directly with sequelize. This seems to conflict with what the [sequelize docs say about $contains](http://docs.sequelizejs.com/manual/tutorial/querying.html#operators). Unless further proof can be provided that feathers is the problem here, I vote that this be closed as a sequelize issue.

**Comment by DesignByOnyx** [comment] 2017-07-21 13:34
I have submitted an issue to the sequelize team: https://github.com/sequelize/sequelize/issues/7992

**Comment by ramsestom** [comment] 2017-07-21 16:30
Just tested with:

```
var query = Object.assign({}, {
        targets: {
            $or: {
                $eq: null,
                $contains: 1
            }
        }
	});

var app = require('./src/app');
	
const myModel = app.service('container').Model;
myModel.findAll(query).then(result => console.log(result)).catch(err => console.log(err));
```

And it is working fine.
Here is the output I have:
```
You are using the default filter for the Container service. For more information about event filters see https://docs.feathersjs.com/api/events.html#event-filtering
(sequelize) Warning: Model attributes (targets) passed into finder method options, but the options.where object is empty. Did you forget to use options.where?
[ container {
    dataValues:
     { id: 1,
       targets: [Object],
       createdAt: 2017-07-21T16:18:51.982Z,
       updatedAt: 2017-07-21T16:18:51.982Z },
    _previousDataValues:
     { id: 1,
       targets: [Object],
       createdAt: 2017-07-21T16:18:51.982Z,
       updatedAt: 2017-07-21T16:18:51.982Z },
    _changed: {},
    _modelOptions:
     { timestamps: true,
       validate: {},
       freezeTableName: true,
       underscored: false,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: {},
       indexes: [],
       name: [Object],
       omitNull: false,
       classMethods: [Object],
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options:
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Object] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  container {
    dataValues:
     { id: 2,
       targets: [Object],
       createdAt: 2017-07-21T16:20:17.030Z,
       updatedAt: 2017-07-21T16:20:17.030Z },
    _previousDataValues:
     { id: 2,
       targets: [Object],
       createdAt: 2017-07-21T16:20:17.030Z,
       updatedAt: 2017-07-21T16:20:17.030Z },
    _changed: {},
    _modelOptions:
     { timestamps: true,
       validate: {},
       freezeTableName: true,
       underscored: false,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: {},
       indexes: [],
       name: [Object],
       omitNull: false,
       classMethods: [Object],
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options:
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Object] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  container {
    dataValues:
     { id: 3,
       targets: null,
       createdAt: 2017-07-21T16:20:28.112Z,
       updatedAt: 2017-07-21T16:20:28.112Z },
    _previousDataValues:
     { id: 3,
       targets: null,
       createdAt: 2017-07-21T16:20:28.112Z,
       updatedAt: 2017-07-21T16:20:28.112Z },
    _changed: {},
    _modelOptions:
     { timestamps: true,
       validate: {},
       freezeTableName: true,
       underscored: false,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: {},
       indexes: [],
       name: [Object],
       omitNull: false,
       classMethods: [Object],
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options:
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Object] },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false } ]
```

The data in my database are:
[
  { "id": 1, "targets": [0, 1, 2] },
  { "id": 2, "targets": [0, 3, 4] },
  { "id": 3, "targets": null }
]

**Comment by ramsestom** [comment] 2017-07-21 16:41
OK tracked down the issue. Seems was missing the `where` clause. And with it actually  `$contains: 1` fails but `$contains: [1]` works. My bad...

**Closed** 2017-07-21 16:53 UTC

**Comment by DesignByOnyx** [comment] 2017-07-21 17:54
Ah - sweet - glad we got to the bottom of it. Thanks for following up on this.
