### ISSUE TITLE
Avoid findAndCount if paginate is false

### ISSUE THREAD

**Issue by eikaramba** [feathersjs/feathers-sequelize#95] opened 2017-03-19 23:44 UTC
Is there a reason why findAndCount is always used and the returned object contains all counts etc. EVEN if pagination is deactivated. I think this makes a good optimization improvement to only use sequelize find() method and reduce half of the calls in this case

**Comment by daffl** [comment] 2017-03-24 22:59
There is indeed no reason. `_find` does need a page object returned but we could just set the `total` to `-1` or something.

**Comment by DesignByOnyx** [comment] 2017-08-02 19:49
I wanted to leave my 2 cents on this. Over the past 6 or 8 months I have been fixing issues caused by multiple code paths - code paths created to achieve what are typically micro-optimizations. These extra code paths are not tested by the shared adapter tests, and as a result have ended up causing more problems and regressions than they solved. 

To satisfy this request, we will need to create another branch of code - one which does `find` in certain situations instead of `findAndCount`. From my understanding of most db engines, count queries should be O:1 if indexes are set up properly as the engine will have the count already stored in the index table. If indexing is not set up properly, db engines have been known to use their own internal cache for subsequent queries (because in the real world, doing a SELECT and then COUNT is very common - engines have optimized for it). Even a stand-alone COUNT query should still be fairly lightweight as no columns are actually selected (assuming data <~ 100K rows) - light enough not to cause a huge performance concern. Much better optimization can be achieved by setting up proper indexing and proper caching schemes. My vote is to leave it as it is unless some tangible benchmarks can be provided to prove that there is a substantial gain.

**Comment by daffl** [comment] 2017-08-14 21:59
Agreed, thank you for you input @DesignByOnyx. Closing but always open to PRs of course.

**Closed by daffl** 2017-08-14 21:59 UTC
